/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 phantoms.glb --transform
*/

import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF,useScroll } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'

export function BottomSpikes01(props) {
  const { nodes, materials } = useGLTF('./models/object/bottom-spikes01-transformed.glb')
  const model3d = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    .to(model3d.current.position, {x: -1.7}, 16.5)
    .to(model3d.current.position, {y: 1}, 16.5)
 

    // .to(model3d.current.rotation, {y: 0}, 20)   
    // .to(model3d.current.rotation, {x: 0}, 20) 
    .to(model3d.current.position, {x: -1.7}, 20)  

  },[])
  
  return (
    <group {...props} dispose={null} ref={model3d}>      
      <mesh geometry={nodes.spikestop.geometry} material={nodes.spikestop.material} position={[0, 0, 0]} rotation={[1*Math.PI/2, 0, 0]} scale={[1, 1, 1]}/>
    </group>
  )
}

useGLTF.preload('./models/object/bottom-spikes01-transformed.glb')
