/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 phantoms.glb --transform
*/

import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF,useScroll } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'

export function DecoFlask(props) {
  const { nodes, materials } = useGLTF('./models/object/deco-flask-transformed.glb')
  const robot = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    .to(robot.current.position, {x: -2.5}, 0)
    .to(robot.current.rotation, {x: -1*Math.PI/3}, 0)
    .to(robot.current.rotation, {y: -2*Math.PI}, 0)
    
    .to(robot.current.rotation, {x: -1*Math.PI/3}, 6)
    .to(robot.current.rotation, {y: -2*Math.PI}, 6)

    .to(robot.current.rotation, {y: 0}, 8)    

    // .to(robot.current.rotation, {x: -1*Math.PI/2}, 20)
    .to(robot.current.position, {x: -2.5}, 20)   

  },[])
  
  return (
    <group {...props} dispose={null} ref={robot}>      
      <mesh geometry={nodes.flask.geometry} material={nodes.flask.material} position={[0, 0, 0]} rotation={[1*Math.PI/2, 0, 0]} scale={[1, 1, 1]}/>
    </group>
  )
}

useGLTF.preload('./models/object/deco-flask-transformed.glb')
