/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 phantoms.glb --transform
*/

import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF,useScroll } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'

export function DecoChatbubble(props) {
  const { nodes, materials } = useGLTF('./models/object/deco-chatbubble-transformed.glb')
  const model3d = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    .to(model3d.current.rotation, {y: 2*Math.PI}, 0)
    .to(model3d.current.position, {x: 2}, 0)

    .to(model3d.current.rotation, {y: 2*Math.PI}, 9)

    .to(model3d.current.rotation, {y: 0}, 11)    

    .to(model3d.current.position, {x: 2}, 20)   

  },[])
  
  return (
    <group {...props} dispose={null} ref={model3d}>      
      <mesh geometry={nodes.chatbubble.geometry} material={nodes.chatbubble.material} position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[1.6, 1.6, .3]}/>
    </group>
  )
}

useGLTF.preload('./models/object/deco-chatbubble-transformed.glb')
